# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46d87f09f934814e2987347fdc01788fc32cf836935d19fceb9ab48b95b4b99c1c28a05a2a87e2b6436868a0cee9a82427c20e02341bbc62ad1e3c16c93639cf

test:
  secret_key_base: 735daf5deb4d213195dad42eac2c7e0a8aef9c83bd47a4f7c13699224a99a7f412321ae0f4efbceb14b0b7451ef53b26e1d6b4483da235479eb0baa868050525

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
